// Seed mock restaurants across SF / the Bay Area.
// Idempotent: clears existing Restaurant rows first, then bulk-inserts.
// Run with: `bun prisma/seed.mjs` (or `bunx prisma db seed`) from backend/.
//
// Tag conventions (kept consistent so the AI can filter/rank reliably):
//   cuisine_tags: lowercase, hyphenated ACTUAL CUISINES only — national or
//                 regional (e.g. 'italian','oaxacan','south-indian') plus the
//                 'seafood' category. NOT dishes ('pizza','dumplings','ramen'),
//                 cooking styles ('wood-fired'), establishment types
//                 ('cafe','bakery','diner'), service styles ('fine-dining'),
//                 meal types ('brunch'), or diets ('vegan'). Primary cuisine first.
//   dietary_tags: controlled vocabulary ONLY — a diet/allergen the restaurant
//                 can accommodate:
//                   'vegan' | 'vegetarian' | 'gluten-free' | 'nut-free'
//                   | 'dairy-free' | 'halal' | 'kosher' | 'shellfish-free'
//   description: one vivid sentence — signature dish + vibe, to aid occasion matching.

import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const HOURS_STD = 'Mon-Sun 11:00-22:00'
const HOURS_LATE = 'Mon-Sun 11:00-00:00'
const HOURS_DINNER = 'Tue-Sun 17:00-22:00'
const HOURS_CAFE = 'Mon-Sun 07:00-19:00'

// price_avg = approximate per-person spend in USD.
const restaurants = [
  // --- San Francisco ---
  { name: 'Nopa', description: 'Wood-fired California cooking in a buzzy, high-ceilinged room — the rotisserie chicken and grilled flatbreads shine.', cuisine_tags: ['american'], dietary_tags: ['vegetarian', 'gluten-free'], price_avg: 55, address: '560 Divisadero St, San Francisco, CA 94117', lat: 37.7749, long: -122.4378, hours: HOURS_LATE, avg_rating: 4.6 },
  { name: 'Gracias Madre', description: 'Warm, plant-based Mexican in the Mission with standout cashew-cheese quesadillas and mezcal cocktails.', cuisine_tags: ['mexican'], dietary_tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free'], price_avg: 35, address: '2211 Mission St, San Francisco, CA 94110', lat: 37.7607, long: -122.4193, hours: HOURS_STD, avg_rating: 4.4 },
  { name: 'Tartine Manufactory', description: 'Airy all-day bakery and cafe renowned for its country bread, morning buns, and seasonal open-faced toasts.', cuisine_tags: ['american'], dietary_tags: ['vegetarian'], price_avg: 28, address: '595 Alabama St, San Francisco, CA 94110', lat: 37.7615, long: -122.4122, hours: HOURS_CAFE, avg_rating: 4.5 },
  { name: 'House of Prime Rib', description: 'A clubby SF institution serving one thing perfectly — prime rib carved tableside from silver zeppelin carts.', cuisine_tags: ['american'], dietary_tags: ['gluten-free', 'nut-free', 'shellfish-free'], price_avg: 65, address: '1906 Van Ness Ave, San Francisco, CA 94109', lat: 37.7939, long: -122.4238, hours: HOURS_DINNER, avg_rating: 4.7 },
  { name: 'Zuni Cafe', description: 'Iconic Mediterranean-Californian bistro famous for its brick-oven roast chicken for two and Caesar salad.', cuisine_tags: ['mediterranean', 'american'], dietary_tags: ['vegetarian', 'gluten-free'], price_avg: 60, address: '1658 Market St, San Francisco, CA 94102', lat: 37.7725, long: -122.4216, hours: HOURS_STD, avg_rating: 4.5 },
  { name: 'La Taqueria', description: 'No-frills Mission legend turning out griddled, rice-free burritos and crispy-shelled tacos al pastor.', cuisine_tags: ['mexican'], dietary_tags: ['gluten-free', 'nut-free', 'shellfish-free'], price_avg: 15, address: '2889 Mission St, San Francisco, CA 94110', lat: 37.7509, long: -122.4181, hours: HOURS_STD, avg_rating: 4.5 },
  { name: 'Burma Superstar', description: 'Bustling Clement St favorite where the hand-tossed tea-leaf salad and coconut chicken noodles draw daily lines.', cuisine_tags: ['burmese'], dietary_tags: ['vegetarian', 'vegan'], price_avg: 30, address: '309 Clement St, San Francisco, CA 94118', lat: 37.7829, long: -122.4636, hours: HOURS_STD, avg_rating: 4.4 },
  { name: 'State Bird Provisions', description: 'Playful, Michelin-starred Californian small plates served dim-sum style off roving carts — book well ahead.', cuisine_tags: ['american'], dietary_tags: ['vegetarian'], price_avg: 70, address: '1529 Fillmore St, San Francisco, CA 94115', lat: 37.7834, long: -122.4324, hours: HOURS_DINNER, avg_rating: 4.6 },
  { name: 'Yank Sing', description: 'Polished Financial District dim sum destination famed for juicy Shanghai soup dumplings and Peking duck.', cuisine_tags: ['chinese'], dietary_tags: ['vegetarian'], price_avg: 40, address: '101 Spear St, San Francisco, CA 94105', lat: 37.7924, long: -122.3937, hours: HOURS_CAFE, avg_rating: 4.3 },
  { name: 'Rich Table', description: 'Intimate Hayes Valley spot beloved for its addictive sardine chips and porcini doughnuts before the theater.', cuisine_tags: ['american'], dietary_tags: ['vegetarian', 'gluten-free'], price_avg: 75, address: '199 Gough St, San Francisco, CA 94102', lat: 37.7739, long: -122.4229, hours: HOURS_DINNER, avg_rating: 4.6 },
  { name: 'Kokkari Estiatorio', description: 'Rustic-elegant Greek taverna with a roaring fireplace — the lamb chops and moussaka make it a special-occasion staple.', cuisine_tags: ['greek', 'mediterranean'], dietary_tags: ['vegetarian', 'gluten-free', 'halal'], price_avg: 65, address: '200 Jackson St, San Francisco, CA 94111', lat: 37.7973, long: -122.3993, hours: HOURS_STD, avg_rating: 4.7 },
  { name: 'Che Fico', description: 'Buzzy, plant-lined NoPa dining room known for wood-fired pizzas and Roman-Jewish antipasti.', cuisine_tags: ['italian'], dietary_tags: ['vegetarian'], price_avg: 60, address: '838 Divisadero St, San Francisco, CA 94117', lat: 37.7766, long: -122.4378, hours: HOURS_DINNER, avg_rating: 4.4 },
  { name: 'Marufuku Ramen', description: 'Japantown ramen-ya pouring silky Hakata tonkotsu broth over thin noodles — expect a wait, it earns it.', cuisine_tags: ['japanese'], dietary_tags: ['shellfish-free'], price_avg: 22, address: '1581 Webster St, San Francisco, CA 94115', lat: 37.7852, long: -122.4318, hours: HOURS_STD, avg_rating: 4.5 },
  { name: 'Delfina', description: 'Beloved Cal-Italian trattoria on 18th St, dependable for handmade pastas and a wood-grilled catch of the day.', cuisine_tags: ['italian'], dietary_tags: ['vegetarian'], price_avg: 55, address: '3621 18th St, San Francisco, CA 94110', lat: 37.7617, long: -122.4243, hours: HOURS_DINNER, avg_rating: 4.4 },
  { name: 'Swan Oyster Depot', description: 'Century-old marble seafood counter with just 18 stools — go for the crab, oysters, and clam chowder.', cuisine_tags: ['seafood'], dietary_tags: ['gluten-free', 'nut-free'], price_avg: 45, address: '1517 Polk St, San Francisco, CA 94109', lat: 37.7906, long: -122.4204, hours: 'Mon-Sat 10:30-17:30', avg_rating: 4.6 },
  { name: 'Foreign Cinema', description: 'Romantic Mission courtyard where Mediterranean-Californian plates are served under classic films projected on the wall.', cuisine_tags: ['mediterranean'], dietary_tags: ['vegetarian', 'gluten-free'], price_avg: 60, address: '2534 Mission St, San Francisco, CA 94110', lat: 37.7562, long: -122.4189, hours: HOURS_STD, avg_rating: 4.4 },
  { name: 'Nari', description: 'Sleek, modern Thai in Japantown from chef Pim Techamuanvivit, with bold shared plates and a stylish crowd.', cuisine_tags: ['thai'], dietary_tags: ['vegetarian', 'vegan', 'gluten-free'], price_avg: 70, address: '1625 Post St, San Francisco, CA 94115', lat: 37.7856, long: -122.4295, hours: HOURS_DINNER, avg_rating: 4.5 },
  { name: "Tommy's Joynt", description: 'Kitschy old-school hofbrau, cash-friendly and casual, piling plates with carved brisket, turkey, and buffalo stew.', cuisine_tags: ['american'], dietary_tags: ['nut-free', 'shellfish-free'], price_avg: 20, address: '1101 Geary Blvd, San Francisco, CA 94109', lat: 37.7862, long: -122.4185, hours: HOURS_LATE, avg_rating: 4.2 },
  { name: 'Zazie', description: 'Cozy Cole Valley French bistro with a heated back patio — a weekend-brunch favorite for gingerbread pancakes.', cuisine_tags: ['french'], dietary_tags: ['vegetarian'], price_avg: 35, address: '941 Cole St, San Francisco, CA 94117', lat: 37.7657, long: -122.4501, hours: HOURS_CAFE, avg_rating: 4.5 },
  { name: 'Pancho Villa Taqueria', description: 'High-energy Mission taqueria slinging overstuffed burritos and a sprawling salsa bar late into the night.', cuisine_tags: ['mexican'], dietary_tags: ['vegetarian', 'gluten-free'], price_avg: 14, address: '3071 16th St, San Francisco, CA 94103', lat: 37.7651, long: -122.4200, hours: HOURS_LATE, avg_rating: 4.3 },
  { name: 'Sotto Mare', description: 'Snug North Beach seafood joint whose "best damn crab cioppino" is a shareable, messy delight.', cuisine_tags: ['italian', 'seafood'], dietary_tags: ['nut-free'], price_avg: 45, address: '552 Green St, San Francisco, CA 94133', lat: 37.7996, long: -122.4089, hours: HOURS_STD, avg_rating: 4.5 },
  { name: 'The Slanted Door', description: 'Refined modern Vietnamese with sweeping Bay views — the shaking beef and spring rolls are perennial orders.', cuisine_tags: ['vietnamese'], dietary_tags: ['vegetarian', 'gluten-free'], price_avg: 65, address: '1 Ferry Building, San Francisco, CA 94111', lat: 37.7956, long: -122.3934, hours: HOURS_STD, avg_rating: 4.3 },
  { name: 'Souvla', description: 'Bright fast-casual Greek turning out rotisserie lamb and chicken pitas, salads, and frozen Greek-yogurt cones.', cuisine_tags: ['greek', 'mediterranean'], dietary_tags: ['vegetarian', 'gluten-free', 'halal'], price_avg: 20, address: '517 Hayes St, San Francisco, CA 94102', lat: 37.7764, long: -122.4247, hours: HOURS_STD, avg_rating: 4.4 },
  { name: "Brenda's French Soul Food", description: 'Homey Polk St spot marrying Creole and Southern cooking — the crawfish beignets and shrimp grits are essential.', cuisine_tags: ['creole', 'southern', 'american'], dietary_tags: ['vegetarian'], price_avg: 25, address: '652 Polk St, San Francisco, CA 94102', lat: 37.7836, long: -122.4189, hours: HOURS_CAFE, avg_rating: 4.4 },
  { name: 'Dosa', description: 'Vibrant South Indian dining room specializing in crispy, yard-long dosas and coastal curries with natural wines.', cuisine_tags: ['indian', 'south-indian'], dietary_tags: ['vegetarian', 'vegan', 'gluten-free'], price_avg: 35, address: '1700 Fillmore St, San Francisco, CA 94115', lat: 37.7846, long: -122.4327, hours: HOURS_STD, avg_rating: 4.2 },

  // --- Oakland / East Bay ---
  { name: 'Commis', description: 'Serene Piedmont Ave tasting-menu room, the East Bay\'s two-Michelin-star flagship for precise, seasonal Californian cuisine.', cuisine_tags: ['american'], dietary_tags: ['vegetarian', 'gluten-free'], price_avg: 150, address: '3859 Piedmont Ave, Oakland, CA 94611', lat: 37.8266, long: -122.2500, hours: HOURS_DINNER, avg_rating: 4.7 },
  { name: 'Fentons Creamery', description: 'Century-old Oakland creamery and diner — a family-friendly stop for towering sundaes and crab-salad sandwiches.', cuisine_tags: ['american'], dietary_tags: ['vegetarian'], price_avg: 20, address: '4226 Piedmont Ave, Oakland, CA 94611', lat: 37.8293, long: -122.2496, hours: HOURS_LATE, avg_rating: 4.5 },
  { name: 'Shan Dong', description: 'Beloved Oakland Chinatown noodle house pulling fresh hand-cut noodles and folding delicate pork dumplings.', cuisine_tags: ['chinese'], dietary_tags: ['vegetarian'], price_avg: 20, address: '328 10th St, Oakland, CA 94607', lat: 37.7986, long: -122.2716, hours: HOURS_STD, avg_rating: 4.3 },
  { name: 'Homeroom', description: 'Cheerful comfort-food spot devoted entirely to mac and cheese, from Gilroy garlic to a spicy Sriracha bowl.', cuisine_tags: ['american'], dietary_tags: ['vegetarian', 'gluten-free', 'nut-free'], price_avg: 22, address: '400 40th St, Oakland, CA 94609', lat: 37.8288, long: -122.2636, hours: HOURS_STD, avg_rating: 4.4 },
  { name: 'Comal', description: 'Lively downtown Berkeley Oaxacan spot with a mezcal-driven bar, wood-grilled meats, and a heated back patio.', cuisine_tags: ['mexican', 'oaxacan'], dietary_tags: ['vegetarian', 'gluten-free'], price_avg: 40, address: '2020 Shattuck Ave, Berkeley, CA 94704', lat: 37.8716, long: -122.2680, hours: HOURS_DINNER, avg_rating: 4.4 },
  { name: 'Chez Panisse', description: 'The birthplace of California cuisine — Alice Waters\'s Berkeley landmark serving a daily-changing, produce-driven menu.', cuisine_tags: ['american', 'french'], dietary_tags: ['vegetarian', 'gluten-free'], price_avg: 125, address: '1517 Shattuck Ave, Berkeley, CA 94709', lat: 37.8794, long: -122.2691, hours: HOURS_DINNER, avg_rating: 4.6 },
  { name: "Vik's Chaat", description: 'Warehouse-sized Berkeley chaat house and grocery, packed at lunch for chole bhature and crispy dahi puri.', cuisine_tags: ['indian'], dietary_tags: ['vegetarian', 'vegan'], price_avg: 18, address: '2390 4th St, Berkeley, CA 94710', lat: 37.8666, long: -122.2996, hours: HOURS_CAFE, avg_rating: 4.4 },
  { name: 'FuseBOX', description: 'Tiny, chef-driven West Oakland Korean spot with soulful banchan, house makgeolli, and a laid-back patio.', cuisine_tags: ['korean'], dietary_tags: ['vegetarian', 'vegan'], price_avg: 30, address: '2311A Magnolia St, Oakland, CA 94607', lat: 37.8130, long: -122.2870, hours: HOURS_DINNER, avg_rating: 4.5 },
  { name: 'Millennium', description: 'Elegant, fully vegan fine-dining room in Rockridge with an inventive, globally inspired seasonal tasting menu.', cuisine_tags: ['american'], dietary_tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free'], price_avg: 70, address: '5912 College Ave, Oakland, CA 94618', lat: 37.8459, long: -122.2519, hours: HOURS_DINNER, avg_rating: 4.5 },
  { name: "Zachary's Chicago Pizza", description: 'East Bay institution famous for its baked-to-order stuffed deep-dish pizza — worth the 30-minute wait.', cuisine_tags: ['italian', 'american'], dietary_tags: ['vegetarian'], price_avg: 25, address: '5801 College Ave, Oakland, CA 94618', lat: 37.8452, long: -122.2523, hours: HOURS_STD, avg_rating: 4.5 },

  // --- Peninsula / South Bay ---
  { name: 'The Village Pub', description: 'Michelin-starred Woodside destination pairing a serious wine cellar with a burger-and-New-American menu.', cuisine_tags: ['american'], dietary_tags: ['vegetarian', 'gluten-free'], price_avg: 85, address: '2967 Woodside Rd, Woodside, CA 94062', lat: 37.4298, long: -122.2540, hours: HOURS_DINNER, avg_rating: 4.5 },
  { name: "Oren's Hummus", description: 'Downtown Palo Alto favorite for silky, house-ground hummus, warm pita, and charred shawarma platters.', cuisine_tags: ['israeli', 'mediterranean'], dietary_tags: ['vegetarian', 'vegan', 'gluten-free', 'halal', 'kosher'], price_avg: 25, address: '261 University Ave, Palo Alto, CA 94301', lat: 37.4459, long: -122.1607, hours: HOURS_STD, avg_rating: 4.3 },
  { name: 'Zola', description: 'Warm Palo Alto bistro serving seasonal French-Californian plates and craft cocktails in a candlelit room.', cuisine_tags: ['french'], dietary_tags: ['vegetarian'], price_avg: 60, address: '565 Bryant St, Palo Alto, CA 94301', lat: 37.4447, long: -122.1618, hours: HOURS_DINNER, avg_rating: 4.4 },
  { name: 'Falafel Stop', description: 'Cult Sunnyvale counter frying crisp, herb-flecked falafel to order and stuffing generous shawarma pitas.', cuisine_tags: ['mediterranean', 'middle-eastern'], dietary_tags: ['vegetarian', 'vegan', 'halal'], price_avg: 15, address: '1325 Sunnyvale Saratoga Rd, Sunnyvale, CA 94087', lat: 37.3610, long: -122.0323, hours: HOURS_STD, avg_rating: 4.5 },
  { name: 'Back A Yard', description: 'Downtown San Jose Caribbean grill fragrant with jerk chicken, oxtail, and fried plantains.', cuisine_tags: ['caribbean', 'jamaican'], dietary_tags: ['gluten-free', 'dairy-free'], price_avg: 25, address: '80 N Market St, San Jose, CA 95113', lat: 37.3369, long: -121.8934, hours: HOURS_STD, avg_rating: 4.4 },
  { name: "Original Joe's", description: 'Old-guard San Jose Italian-American, tuxedoed servers and red booths, known for its charbroiled burger and chicken parm.', cuisine_tags: ['italian', 'american'], dietary_tags: ['vegetarian'], price_avg: 40, address: '301 S 1st St, San Jose, CA 95113', lat: 37.3320, long: -121.8863, hours: HOURS_LATE, avg_rating: 4.4 },
  { name: "Bill's Cafe", description: 'Cheerful San Jose breakfast spot with all-day pancakes, hearty omelets, and a bustling weekend patio.', cuisine_tags: ['american'], dietary_tags: ['vegetarian'], price_avg: 20, address: '1115 Willow St, San Jose, CA 95125', lat: 37.3110, long: -121.8975, hours: HOURS_CAFE, avg_rating: 4.4 },
  { name: 'Din Tai Fung', description: 'The famed Taiwanese chain where you can watch chefs pleat delicate xiao long bao behind glass — expect a wait.', cuisine_tags: ['taiwanese', 'chinese'], dietary_tags: ['vegetarian'], price_avg: 35, address: '2855 Stevens Creek Blvd, Santa Clara, CA 95050', lat: 37.3230, long: -121.9490, hours: HOURS_STD, avg_rating: 4.5 },
  { name: 'Pho Kim Long', description: 'Cavernous, always-open San Jose pho house ladling deeply aromatic beef broth over rice noodles.', cuisine_tags: ['vietnamese'], dietary_tags: ['gluten-free', 'dairy-free'], price_avg: 18, address: '1215 Lick Ave, San Jose, CA 95110', lat: 37.3130, long: -121.8790, hours: HOURS_LATE, avg_rating: 4.2 },
  { name: "Sushi Sam's Edomata", description: 'Traditional San Mateo sushi bar prized for pristine, market-fresh nigiri and daily-special omakase.', cuisine_tags: ['japanese'], dietary_tags: ['gluten-free', 'dairy-free'], price_avg: 55, address: '218 E 3rd Ave, San Mateo, CA 94401', lat: 37.5652, long: -122.3235, hours: HOURS_DINNER, avg_rating: 4.6 },

  // --- Marin / North Bay ---
  { name: 'Sol Food', description: 'Sunny San Rafael Puerto Rican kitchen famous for its garlicky pollo al ajillo sandwich and sweet plantains.', cuisine_tags: ['puerto-rican', 'caribbean'], dietary_tags: ['gluten-free', 'vegetarian', 'dairy-free'], price_avg: 25, address: '901 Lincoln Ave, San Rafael, CA 94901', lat: 37.9762, long: -122.5222, hours: HOURS_STD, avg_rating: 4.5 },
  { name: 'Sushi Ran', description: 'Sausalito\'s destination sushi bar blending traditional Edomae technique with a well-curated sake list.', cuisine_tags: ['japanese'], dietary_tags: ['gluten-free', 'dairy-free'], price_avg: 80, address: '107 Caledonia St, Sausalito, CA 94965', lat: 37.8570, long: -122.4850, hours: HOURS_DINNER, avg_rating: 4.6 },
  { name: 'Fish.', description: 'Waterfront Sausalito seafood shack serving sustainable catch, a killer crab roll, and cash-only harbor views.', cuisine_tags: ['seafood'], dietary_tags: ['gluten-free'], price_avg: 45, address: '350 Harbor Dr, Sausalito, CA 94965', lat: 37.8637, long: -122.4820, hours: HOURS_STD, avg_rating: 4.4 },
  { name: 'Bar Bocce', description: 'Casual bayside spot with wood-fired pizzas, a sandy bocce court, and Adirondack chairs at the water\'s edge.', cuisine_tags: ['italian'], dietary_tags: ['vegetarian'], price_avg: 35, address: '1250 Bridgeway, Sausalito, CA 94965', lat: 37.8620, long: -122.4835, hours: HOURS_STD, avg_rating: 4.3 },

  // --- More San Francisco ---
  { name: 'Trestle', description: 'Great-value Jackson Square spot offering a nightly-changing three-course prix fixe of rustic New American plates.', cuisine_tags: ['american'], dietary_tags: ['vegetarian'], price_avg: 45, address: '531 Jackson St, San Francisco, CA 94133', lat: 37.7969, long: -122.4037, hours: HOURS_DINNER, avg_rating: 4.3 },
  { name: 'Lers Ros', description: 'Bustling Tenderloin Thai kitchen with an encyclopedic menu and fiery, no-holds-barred northeastern dishes.', cuisine_tags: ['thai'], dietary_tags: ['vegetarian', 'vegan', 'gluten-free'], price_avg: 28, address: '730 Larkin St, San Francisco, CA 94109', lat: 37.7838, long: -122.4173, hours: HOURS_LATE, avg_rating: 4.3 },
  { name: 'El Farolito', description: 'Late-night Mission taqueria whose foil-wrapped super burritos and al pastor quesadillas fuel the neighborhood past midnight.', cuisine_tags: ['mexican'], dietary_tags: ['vegetarian', 'gluten-free'], price_avg: 13, address: '2779 Mission St, San Francisco, CA 94110', lat: 37.7524, long: -122.4184, hours: HOURS_LATE, avg_rating: 4.4 },
  { name: 'Good Mong Kok', description: 'Grab-and-go Chinatown dim sum bakery with a fast-moving line for hot shrimp har gow and pork buns.', cuisine_tags: ['chinese'], dietary_tags: ['vegetarian'], price_avg: 12, address: '1039 Stockton St, San Francisco, CA 94108', lat: 37.7959, long: -122.4079, hours: HOURS_CAFE, avg_rating: 4.4 },
  { name: "Al's Place", description: 'Michelin-starred, vegetable-forward Mission tasting spot where sides are the stars and meat plays a supporting role.', cuisine_tags: ['american'], dietary_tags: ['vegetarian', 'vegan', 'gluten-free'], price_avg: 65, address: '1499 Valencia St, San Francisco, CA 94110', lat: 37.7488, long: -122.4207, hours: HOURS_DINNER, avg_rating: 4.4 },
  { name: 'Kin Khao', description: 'Michelin-starred modern Thai off Union Square, using local ingredients for punchy curries and pork-belly relish.', cuisine_tags: ['thai'], dietary_tags: ['vegetarian', 'gluten-free'], price_avg: 45, address: '55 Cyril Magnin St, San Francisco, CA 94102', lat: 37.7855, long: -122.4090, hours: HOURS_DINNER, avg_rating: 4.4 },
  { name: 'Farmhouse Kitchen Thai', description: 'Festive, flower-draped Mission dining room dishing colorful Thai plates and photogenic Instagram-famous cocktails.', cuisine_tags: ['thai'], dietary_tags: ['vegetarian', 'vegan', 'gluten-free'], price_avg: 40, address: '710 Florida St, San Francisco, CA 94110', lat: 37.7597, long: -122.4110, hours: HOURS_STD, avg_rating: 4.5 },
  { name: 'Tadich Grill', description: 'California\'s oldest continuously running restaurant — a wood-paneled FiDi grill known for cioppino and sand dabs.', cuisine_tags: ['seafood', 'american'], dietary_tags: ['gluten-free'], price_avg: 55, address: '240 California St, San Francisco, CA 94111', lat: 37.7932, long: -122.3990, hours: HOURS_STD, avg_rating: 4.3 },

  // --- Expanded cuisine coverage (Bay Area, one+ per new cuisine) ---
  { name: 'Austin\'s Homestyle', description: 'Smoky central-Texas-style brisket, ribs, and jalapeño sausage served by the pound on butcher paper.', cuisine_tags: ['barbecue'], dietary_tags: ['gluten-free', 'dairy-free'], price_avg: 30, address: '1900 University Ave, Berkeley, CA 94704', lat: 37.8715, long: -122.2730, hours: HOURS_STD, avg_rating: 4.4 },
  { name: 'Old Jerusalem', description: 'Family-run Palestinian kitchen in the Mission for hummus, maqluba, and charcoal-grilled kebabs.', cuisine_tags: ['palestinian', 'middle-eastern'], dietary_tags: ['vegetarian', 'vegan', 'halal'], price_avg: 22, address: '2966 Mission St, San Francisco, CA 94110', lat: 37.7503, long: -122.4184, hours: HOURS_STD, avg_rating: 4.4 },
  { name: 'Aslam\'s Rasoi', description: 'Bustling Valencia St spot for Pakistani karahi, seekh kebabs, and buttery garlic naan.', cuisine_tags: ['pakistani'], dietary_tags: ['halal', 'vegetarian', 'gluten-free'], price_avg: 25, address: '1037 Valencia St, San Francisco, CA 94110', lat: 37.7562, long: -122.4210, hours: HOURS_STD, avg_rating: 4.3 },
  { name: 'Kingdom of Dumpling', description: 'Outer Sunset hole-in-the-wall famous for hand-folded northern-Chinese boiled dumplings.', cuisine_tags: ['chinese', 'shanghainese'], dietary_tags: ['vegetarian'], price_avg: 18, address: '1713 Taraval St, San Francisco, CA 94116', lat: 37.7423, long: -122.4832, hours: HOURS_STD, avg_rating: 4.2 },
  { name: 'Limón', description: 'Vibrant Peruvian dining room for lomo saltado, ceviche, and pisco sours.', cuisine_tags: ['peruvian'], dietary_tags: ['gluten-free', 'dairy-free'], price_avg: 35, address: '1001 S Van Ness Ave, San Francisco, CA 94110', lat: 37.7556, long: -122.4166, hours: HOURS_DINNER, avg_rating: 4.3 },
  { name: 'Fogo de Chão', description: 'Brazilian churrascaria where gauchos carve fire-roasted meats tableside beside a lavish salad bar.', cuisine_tags: ['brazilian'], dietary_tags: ['gluten-free', 'nut-free'], price_avg: 70, address: '201 S Market St, San Jose, CA 95113', lat: 37.3320, long: -121.8890, hours: HOURS_DINNER, avg_rating: 4.5 },
  { name: 'Espetus Churrascaria', description: 'All-you-can-eat Brazilian rodizio near the Symphony, with skewers of picanha and grilled pineapple.', cuisine_tags: ['brazilian'], dietary_tags: ['gluten-free'], price_avg: 65, address: '1686 Market St, San Francisco, CA 94102', lat: 37.7726, long: -122.4218, hours: HOURS_DINNER, avg_rating: 4.4 },
  { name: 'El Sur', description: 'Empanada cart-turned-shop selling flaky Argentine empanadas with chimichurri.', cuisine_tags: ['argentine'], dietary_tags: ['nut-free'], price_avg: 15, address: '699 Valencia St, San Francisco, CA 94110', lat: 37.7615, long: -122.4216, hours: HOURS_STD, avg_rating: 4.5 },
  { name: 'Beit Rima', description: 'Sunny Castro spot for Levantine comfort food — mujadara, msakhan, and crispy chicken.', cuisine_tags: ['lebanese', 'middle-eastern'], dietary_tags: ['vegetarian', 'vegan', 'halal', 'gluten-free'], price_avg: 28, address: '138 Church St, San Francisco, CA 94114', lat: 37.7679, long: -122.4288, hours: HOURS_STD, avg_rating: 4.4 },
  { name: 'Kitava', description: 'Bright, fully allergen-conscious kitchen serving globally inspired bowls free of gluten, dairy, and refined sugar.', cuisine_tags: ['american'], dietary_tags: ['gluten-free', 'dairy-free', 'nut-free', 'vegan', 'vegetarian'], price_avg: 24, address: '2011 Mission St, San Francisco, CA 94110', lat: 37.7628, long: -122.4193, hours: HOURS_STD, avg_rating: 4.3 },
  { name: 'Teni East Kitchen', description: 'Modern Burmese-Shan cooking in Oakland with tea-leaf salad and pork-belly curry in a stylish room.', cuisine_tags: ['burmese', 'shan'], dietary_tags: ['vegetarian', 'vegan', 'gluten-free'], price_avg: 30, address: '4015 Broadway, Oakland, CA 94611', lat: 37.8286, long: -122.2637, hours: HOURS_DINNER, avg_rating: 4.4 },
  { name: 'Zamzam Kabab House', description: 'Cozy Afghan kitchen for kabuli palaw, mantu dumplings, and charcoal lamb kebabs.', cuisine_tags: ['afghan'], dietary_tags: ['halal', 'vegetarian', 'gluten-free'], price_avg: 24, address: '4113 Geary Blvd, San Francisco, CA 94118', lat: 37.7810, long: -122.4640, hours: HOURS_STD, avg_rating: 4.4 },
  { name: 'Cafe Ethiopia', description: 'Long-running Mission Ethiopian spot serving spongy injera with spicy doro wat and veggie combos.', cuisine_tags: ['ethiopian'], dietary_tags: ['vegetarian', 'vegan', 'gluten-free', 'dairy-free'], price_avg: 22, address: '878 Valencia St, San Francisco, CA 94110', lat: 37.7592, long: -122.4213, hours: HOURS_STD, avg_rating: 4.3 },
  { name: 'Cordon Bleu', description: 'Tiny, decades-old Nob Hill counter for five-spice roast chicken over rice.', cuisine_tags: ['vietnamese'], dietary_tags: ['dairy-free'], price_avg: 15, address: '1574 California St, San Francisco, CA 94109', lat: 37.7907, long: -122.4207, hours: HOURS_STD, avg_rating: 4.4 },
  { name: 'Pearl River', description: 'Cantonese seafood house in the Richmond known for salt-and-pepper crab and clay-pot rice.', cuisine_tags: ['chinese', 'cantonese'], dietary_tags: ['gluten-free'], price_avg: 30, address: '5900 Geary Blvd, San Francisco, CA 94121', lat: 37.7803, long: -122.4790, hours: HOURS_STD, avg_rating: 4.2 },
  { name: 'Spices!', description: 'Fiery Sichuan-Chinese menu in the Richmond stacked with mala hot pots and dan dan noodles.', cuisine_tags: ['chinese', 'sichuan'], dietary_tags: ['vegetarian', 'vegan'], price_avg: 25, address: '291 6th Ave, San Francisco, CA 94118', lat: 37.7830, long: -122.4640, hours: HOURS_STD, avg_rating: 4.2 },
  { name: 'Pagan', description: 'Richmond District Burmese kitchen popular for its samusa soup and tea-leaf salad.', cuisine_tags: ['burmese'], dietary_tags: ['vegetarian', 'vegan', 'gluten-free'], price_avg: 24, address: '3199 Clement St, San Francisco, CA 94121', lat: 37.7820, long: -122.4930, hours: HOURS_STD, avg_rating: 4.2 },
  { name: 'Nrisha Café', description: 'Ashby-area Bangladeshi kitchen for fish curry, kacchi biryani, and dal on weekend specials.', cuisine_tags: ['bangladeshi'], dietary_tags: ['halal', 'vegetarian', 'gluten-free'], price_avg: 20, address: '3126 Shattuck Ave, Berkeley, CA 94705', lat: 37.8530, long: -122.2670, hours: HOURS_STD, avg_rating: 4.2 },
  { name: 'Tanglad', description: 'Modern Filipino kitchen in Berkeley plating adobo, kare-kare, and ube desserts.', cuisine_tags: ['filipino'], dietary_tags: ['gluten-free', 'dairy-free'], price_avg: 30, address: '1799 University Ave, Berkeley, CA 94703', lat: 37.8720, long: -122.2740, hours: HOURS_DINNER, avg_rating: 4.4 },
  { name: 'Rijltje', description: 'Snug spot for an Indonesian rijsttafel spread — rendang, satay, and sambal-laced sides.', cuisine_tags: ['indonesian'], dietary_tags: ['gluten-free', 'dairy-free'], price_avg: 32, address: '2214 Polk St, San Francisco, CA 94109', lat: 37.7960, long: -122.4220, hours: HOURS_DINNER, avg_rating: 4.3 },
  { name: 'Hawker Fare', description: 'Casual Isan-Lao rice bowls and papaya salad from chef James Syhabout in the Mission.', cuisine_tags: ['lao'], dietary_tags: ['gluten-free', 'vegetarian'], price_avg: 28, address: '680 Valencia St, San Francisco, CA 94110', lat: 37.7620, long: -122.4215, hours: HOURS_DINNER, avg_rating: 4.2 },
  { name: 'Kaiyō', description: 'Nikkei (Japanese-Peruvian) dining room with lush decor, tiradito, and pisco-forward cocktails.', cuisine_tags: ['nikkei', 'peruvian', 'japanese'], dietary_tags: ['gluten-free', 'dairy-free'], price_avg: 60, address: '1838 Union St, San Francisco, CA 94123', lat: 37.7975, long: -122.4310, hours: HOURS_DINNER, avg_rating: 4.5 },
  { name: 'Old Mandarin Islamic', description: 'Outer Sunset spot for halal northern-Chinese hot pot and hand-pulled lamb dishes.', cuisine_tags: ['chinese', 'halal-chinese'], dietary_tags: ['halal'], price_avg: 30, address: '3132 Vicente St, San Francisco, CA 94116', lat: 37.7385, long: -122.5010, hours: HOURS_DINNER, avg_rating: 4.2 },
  { name: 'Kholee BBQ', description: 'Korean barbecue in Oakland where you grill marinated galbi and pork belly at the table.', cuisine_tags: ['korean'], dietary_tags: ['gluten-free'], price_avg: 40, address: '372 8th St, Oakland, CA 94607', lat: 37.7995, long: -122.2720, hours: HOURS_DINNER, avg_rating: 4.3 },
  { name: 'La Santaneca', description: 'Excelsior pupuseria griddling cheese-and-loroco pupusas with curtido and salsa roja.', cuisine_tags: ['salvadoran'], dietary_tags: ['vegetarian', 'gluten-free'], price_avg: 15, address: '3781 Mission St, San Francisco, CA 94110', lat: 37.7360, long: -122.4230, hours: HOURS_STD, avg_rating: 4.4 },
  { name: 'Bissap Baobab', description: 'Colorful Senegalese-West African kitchen and bar for thieboudienne and hibiscus juice.', cuisine_tags: ['senegalese', 'west-african'], dietary_tags: ['vegetarian', 'vegan', 'gluten-free', 'dairy-free'], price_avg: 28, address: '3372 19th St, San Francisco, CA 94110', lat: 37.7602, long: -122.4210, hours: HOURS_DINNER, avg_rating: 4.2 },
  { name: 'Troya', description: 'Inner Richmond Turkish spot for lamb adana, mezze, and manti dumplings.', cuisine_tags: ['turkish', 'mediterranean'], dietary_tags: ['vegetarian', 'halal', 'gluten-free'], price_avg: 30, address: '349 Clement St, San Francisco, CA 94118', lat: 37.7828, long: -122.4640, hours: HOURS_STD, avg_rating: 4.3 },
  { name: 'Kronnerburger', description: 'Cult Oakland burger counter with a dry-aged patty, bone marrow, and crisp fries.', cuisine_tags: ['american'], dietary_tags: ['vegetarian', 'gluten-free'], price_avg: 25, address: '4063 Piedmont Ave, Oakland, CA 94611', lat: 37.8283, long: -122.2540, hours: HOURS_DINNER, avg_rating: 4.3 },
  { name: 'Aziza', description: 'Refined Cal-Moroccan destination in the Outer Richmond for basteeya, tagines, and saffron cocktails.', cuisine_tags: ['moroccan'], dietary_tags: ['vegetarian', 'vegan', 'gluten-free', 'halal'], price_avg: 60, address: '5800 Geary Blvd, San Francisco, CA 94121', lat: 37.7802, long: -122.4788, hours: HOURS_DINNER, avg_rating: 4.4 },
  { name: 'Bevri', description: 'Bright Palo Alto kitchen for Georgian khachapuri cheese boats and soup dumplings (khinkali).', cuisine_tags: ['georgian'], dietary_tags: ['vegetarian'], price_avg: 35, address: '162 University Ave, Palo Alto, CA 94301', lat: 37.4460, long: -122.1620, hours: HOURS_DINNER, avg_rating: 4.4 },
  { name: 'Mensho Tokyo', description: 'Tenderloin outpost of the Tokyo ramen phenom, famed for lamb-broth and truffle bowls.', cuisine_tags: ['japanese'], dietary_tags: ['shellfish-free'], price_avg: 24, address: '672 Geary St, San Francisco, CA 94102', lat: 37.7866, long: -122.4145, hours: HOURS_STD, avg_rating: 4.4 },
  { name: 'Little Star Pizza', description: 'Divisadero favorite for cornmeal-crusted Chicago deep-dish and thin-crust pies.', cuisine_tags: ['italian', 'american'], dietary_tags: ['vegetarian'], price_avg: 25, address: '846 Divisadero St, San Francisco, CA 94117', lat: 37.7768, long: -122.4380, hours: HOURS_DINNER, avg_rating: 4.4 },
  { name: 'Barcha', description: 'Downtown Spanish-Mediterranean tapas bar for paella, jamón, and gilda pintxos.', cuisine_tags: ['spanish', 'mediterranean'], dietary_tags: ['vegetarian', 'gluten-free'], price_avg: 45, address: '28 Fremont St, San Francisco, CA 94105', lat: 37.7910, long: -122.3970, hours: HOURS_DINNER, avg_rating: 4.2 },
  { name: 'Bdistro Central Parking', description: 'Tenderloin banh mi and Vietnamese-coffee counter with a cult grilled-pork sandwich.', cuisine_tags: ['vietnamese'], dietary_tags: ['dairy-free'], price_avg: 12, address: '478 Ellis St, San Francisco, CA 94102', lat: 37.7845, long: -122.4150, hours: HOURS_CAFE, avg_rating: 4.4 },
  { name: 'Pica Pica', description: 'Venezuelan arepa and cachapa spot with gluten-free corn pockets and plantains.', cuisine_tags: ['venezuelan'], dietary_tags: ['gluten-free', 'vegetarian', 'vegan', 'dairy-free'], price_avg: 18, address: '401 Valencia St, San Francisco, CA 94103', lat: 37.7670, long: -122.4220, hours: HOURS_STD, avg_rating: 4.3 },
  { name: 'Helmand Palace', description: 'Elegant Russian Hill Afghan restaurant known for kaddo (pumpkin) and aushak dumplings.', cuisine_tags: ['afghan'], dietary_tags: ['halal', 'vegetarian', 'gluten-free'], price_avg: 35, address: '2424 Van Ness Ave, San Francisco, CA 94109', lat: 37.7975, long: -122.4240, hours: HOURS_DINNER, avg_rating: 4.4 },
]

async function main() {
  console.log(`Seeding ${restaurants.length} restaurants...`)
  // Idempotent reset. TRUNCATE ... RESTART IDENTITY resets the id sequence so
  // ids always start at 1 in order; CASCADE clears dependent Event /
  // RecommendationItem rows that reference Restaurant.
  await prisma.$executeRawUnsafe(
    'TRUNCATE TABLE "Restaurant" RESTART IDENTITY CASCADE'
  )

  const result = await prisma.restaurant.createMany({ data: restaurants })
  console.log(`Inserted ${result.count} restaurants.`)

  const total = await prisma.restaurant.count()
  console.log(`Total restaurants in DB: ${total}`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exitCode = 1
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
