// Seed mock restaurants across SF / the Bay Area.
// Idempotent: TRUNCATE ... RESTART IDENTITY resets ids to start at 1 in order,
// CASCADE clears dependent Event / RecommendationItem rows.
// Run with `bun prisma/seed.mjs` from backend/.
//
// Tag conventions:
//   cuisine_tags: broad cuisine, specific region
//   dietary_tags: controlled vocabulary ONLY — a diet/allergen the restaurant
//                 can accommodate:
//                   'vegan' | 'vegetarian' | 'gluten-free' | 'nut-free'
//                   | 'dairy-free' | 'halal' | 'kosher' | 'shellfish-free'
//   description: one vivid sentence — signature dish + vibe.

import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// price_avg = approximate per-person spend in USD.
const restaurants = [
  // --- San Francisco ---
  { name: 'Gracias Madre', description: 'Warm, plant-based Oaxacan-Mexican in the Mission with cashew-cheese quesadillas and mezcal cocktails.', cuisine_tags: ['mexican', 'oaxacan'], dietary_tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free'], price_avg: 35, address: '2211 Mission St, San Francisco, CA 94110', lat: 37.7607, long: -122.4193, hours: 'Mon-Sun 11:00-22:00', avg_rating: 4.4 },
  { name: 'La Taqueria', description: 'No-frills Mission legend for griddled, rice-free Baja-style burritos and tacos al pastor.', cuisine_tags: ['mexican', 'baja'], dietary_tags: ['gluten-free', 'nut-free', 'shellfish-free'], price_avg: 15, address: '2889 Mission St, San Francisco, CA 94110', lat: 37.7509, long: -122.4181, hours: 'Mon-Sun 11:00-22:00', avg_rating: 4.5 },
  { name: 'El Farolito', description: 'Late-night Mission taqueria whose foil-wrapped super burritos fuel the neighborhood past midnight.', cuisine_tags: ['mexican', 'baja'], dietary_tags: ['vegetarian', 'gluten-free'], price_avg: 13, address: '2779 Mission St, San Francisco, CA 94110', lat: 37.7524, long: -122.4184, hours: 'Mon-Sun 11:00-00:00', avg_rating: 4.4 },
  { name: 'Marufuku Ramen', description: 'Japantown ramen-ya pouring silky Hakata-style tonkotsu broth over thin noodles.', cuisine_tags: ['japanese', 'hakata-ramen'], dietary_tags: ['shellfish-free'], price_avg: 22, address: '1581 Webster St, San Francisco, CA 94115', lat: 37.7852, long: -122.4318, hours: 'Mon-Sun 11:00-22:00', avg_rating: 4.5 },
  { name: 'Mensho Tokyo', description: 'Tenderloin outpost of the Tokyo ramen phenom, famed for lamb-broth and truffle bowls.', cuisine_tags: ['japanese', 'tokyo-ramen'], dietary_tags: ['shellfish-free'], price_avg: 24, address: '672 Geary St, San Francisco, CA 94102', lat: 37.7866, long: -122.4145, hours: 'Mon-Sun 11:00-22:00', avg_rating: 4.4 },
  { name: 'Yank Sing', description: 'Polished Financial District dim sum house famed for Shanghai soup dumplings and Peking duck.', cuisine_tags: ['chinese', 'cantonese'], dietary_tags: ['vegetarian'], price_avg: 40, address: '101 Spear St, San Francisco, CA 94105', lat: 37.7924, long: -122.3937, hours: 'Mon-Sun 07:00-19:00', avg_rating: 4.3 },
  { name: 'Good Mong Kok', description: 'Grab-and-go Chinatown dim sum bakery with a fast line for shrimp har gow and pork buns.', cuisine_tags: ['chinese', 'cantonese'], dietary_tags: ['vegetarian'], price_avg: 12, address: '1039 Stockton St, San Francisco, CA 94108', lat: 37.7959, long: -122.4079, hours: 'Mon-Sun 07:00-19:00', avg_rating: 4.4 },
  { name: 'Spices!', description: 'Fiery Richmond District menu stacked with numbing mala hot pots and dan dan noodles.', cuisine_tags: ['chinese', 'sichuan'], dietary_tags: ['vegetarian', 'vegan'], price_avg: 25, address: '291 6th Ave, San Francisco, CA 94118', lat: 37.7830, long: -122.4640, hours: 'Mon-Sun 11:00-22:00', avg_rating: 4.2 },
  { name: 'Z & Y Restaurant', description: 'Chinatown Sichuan destination for chili-oil wontons and mouth-numbing "explosive" chicken.', cuisine_tags: ['chinese', 'sichuan'], dietary_tags: ['vegetarian'], price_avg: 30, address: '655 Jackson St, San Francisco, CA 94133', lat: 37.7961, long: -122.4065, hours: 'Mon-Sun 11:00-22:00', avg_rating: 4.3 },
  { name: 'Kingdom of Dumpling', description: 'Outer Sunset hole-in-the-wall for hand-folded northern-Chinese boiled dumplings.', cuisine_tags: ['chinese', 'shanghainese'], dietary_tags: ['vegetarian'], price_avg: 18, address: '1713 Taraval St, San Francisco, CA 94116', lat: 37.7423, long: -122.4832, hours: 'Mon-Sun 11:00-22:00', avg_rating: 4.2 },
  { name: 'The Slanted Door', description: 'Refined modern Vietnamese with Bay views — the shaking beef and spring rolls are perennial orders.', cuisine_tags: ['vietnamese'], dietary_tags: ['vegetarian', 'gluten-free'], price_avg: 65, address: '1 Ferry Building, San Francisco, CA 94111', lat: 37.7956, long: -122.3934, hours: 'Mon-Sun 11:00-22:00', avg_rating: 4.3 },
  { name: 'Cordon Bleu', description: 'Tiny, decades-old Nob Hill counter for five-spice roast chicken over rice.', cuisine_tags: ['vietnamese'], dietary_tags: ['dairy-free'], price_avg: 15, address: '1574 California St, San Francisco, CA 94109', lat: 37.7907, long: -122.4207, hours: 'Mon-Sun 11:00-22:00', avg_rating: 4.4 },
  { name: 'Lers Ros', description: 'Bustling Tenderloin kitchen with fiery northeastern Isan larb and grilled meats.', cuisine_tags: ['thai', 'isan-thai'], dietary_tags: ['vegetarian', 'vegan', 'gluten-free'], price_avg: 28, address: '730 Larkin St, San Francisco, CA 94109', lat: 37.7838, long: -122.4173, hours: 'Mon-Sun 11:00-00:00', avg_rating: 4.3 },
  { name: 'Kin Khao', description: 'Michelin-starred Bangkok-style Thai off Union Square, with punchy curries and pork-belly relish.', cuisine_tags: ['thai', 'bangkok-thai'], dietary_tags: ['vegetarian', 'gluten-free'], price_avg: 45, address: '55 Cyril Magnin St, San Francisco, CA 94102', lat: 37.7855, long: -122.4090, hours: 'Tue-Sun 17:00-22:00', avg_rating: 4.4 },
  { name: 'Burma Superstar', description: 'Clement St favorite where the hand-tossed tea-leaf salad and coconut chicken noodles draw daily lines.', cuisine_tags: ['burmese'], dietary_tags: ['vegetarian', 'vegan'], price_avg: 30, address: '309 Clement St, San Francisco, CA 94118', lat: 37.7829, long: -122.4636, hours: 'Mon-Sun 11:00-22:00', avg_rating: 4.4 },
  { name: 'Dosa', description: 'Vibrant dining room specializing in crispy, yard-long South Indian dosas and coastal curries.', cuisine_tags: ['indian', 'south-indian'], dietary_tags: ['vegetarian', 'vegan', 'gluten-free'], price_avg: 35, address: '1700 Fillmore St, San Francisco, CA 94115', lat: 37.7846, long: -122.4327, hours: 'Mon-Sun 11:00-22:00', avg_rating: 4.2 },
  { name: 'August 1 Five', description: 'Upscale regional Indian dining with Punjabi butter chicken and modern cocktails.', cuisine_tags: ['indian', 'punjabi'], dietary_tags: ['vegetarian', 'vegan', 'gluten-free', 'halal'], price_avg: 45, address: '524 Van Ness Ave, San Francisco, CA 94102', lat: 37.7813, long: -122.4200, hours: 'Tue-Sun 17:00-22:00', avg_rating: 4.2 },
  { name: 'Che Fico', description: 'Buzzy, plant-lined NoPa room known for wood-fired pizzas and Roman-Jewish antipasti.', cuisine_tags: ['italian', 'roman'], dietary_tags: ['vegetarian'], price_avg: 60, address: '838 Divisadero St, San Francisco, CA 94117', lat: 37.7766, long: -122.4378, hours: 'Tue-Sun 17:00-22:00', avg_rating: 4.4 },
  { name: 'Tony\'s Pizza Napoletana', description: 'North Beach pizzaiolo\'s temple to blistered, wood-fired Neapolitan pies.', cuisine_tags: ['italian', 'neapolitan'], dietary_tags: ['vegetarian'], price_avg: 35, address: '1570 Stockton St, San Francisco, CA 94133', lat: 37.8003, long: -122.4090, hours: 'Mon-Sun 11:00-22:00', avg_rating: 4.4 },
  { name: 'Delfina', description: 'Beloved Mission trattoria dependable for Tuscan handmade pastas and a wood-grilled catch.', cuisine_tags: ['italian', 'tuscan'], dietary_tags: ['vegetarian'], price_avg: 55, address: '3621 18th St, San Francisco, CA 94110', lat: 37.7617, long: -122.4243, hours: 'Tue-Sun 17:00-22:00', avg_rating: 4.4 },
  { name: 'Seven Hills', description: 'Intimate Russian Hill spot for northern-Italian house-made pastas and osso buco.', cuisine_tags: ['italian', 'northern-italian'], dietary_tags: ['vegetarian'], price_avg: 55, address: '1550 Hyde St, San Francisco, CA 94109', lat: 37.7967, long: -122.4189, hours: 'Tue-Sun 17:00-22:00', avg_rating: 4.4 },
  { name: 'Kokkari Estiatorio', description: 'Rustic-elegant Aegean-Greek taverna with a roaring fireplace and standout lamb chops.', cuisine_tags: ['greek', 'aegean-greek'], dietary_tags: ['vegetarian', 'gluten-free', 'halal'], price_avg: 65, address: '200 Jackson St, San Francisco, CA 94111', lat: 37.7973, long: -122.3993, hours: 'Mon-Sun 11:00-22:00', avg_rating: 4.7 },
  { name: 'Souvla', description: 'Bright fast-casual Greek turning out rotisserie lamb pitas, salads, and frozen Greek-yogurt cones.', cuisine_tags: ['greek'], dietary_tags: ['vegetarian', 'gluten-free', 'halal'], price_avg: 20, address: '517 Hayes St, San Francisco, CA 94102', lat: 37.7764, long: -122.4247, hours: 'Mon-Sun 11:00-22:00', avg_rating: 4.4 },
  { name: 'Zuni Cafe', description: 'Iconic Californian bistro famous for its brick-oven roast chicken for two and Caesar salad.', cuisine_tags: ['american'], dietary_tags: ['vegetarian', 'gluten-free'], price_avg: 60, address: '1658 Market St, San Francisco, CA 94102', lat: 37.7725, long: -122.4216, hours: 'Mon-Sun 11:00-22:00', avg_rating: 4.5 },
  { name: 'Nopa', description: 'Wood-fired Californian cooking in a buzzy, high-ceilinged room — the rotisserie chicken shines.', cuisine_tags: ['american'], dietary_tags: ['vegetarian', 'gluten-free'], price_avg: 55, address: '560 Divisadero St, San Francisco, CA 94117', lat: 37.7749, long: -122.4378, hours: 'Mon-Sun 11:00-00:00', avg_rating: 4.6 },
  { name: 'House of Prime Rib', description: 'A clubby SF institution serving prime rib carved tableside from silver zeppelin carts.', cuisine_tags: ['american'], dietary_tags: ['gluten-free', 'nut-free', 'shellfish-free'], price_avg: 65, address: '1906 Van Ness Ave, San Francisco, CA 94109', lat: 37.7939, long: -122.4238, hours: 'Tue-Sun 17:00-22:00', avg_rating: 4.7 },
  { name: 'Brenda\'s French Soul Food', description: 'Homey Polk St spot marrying Creole and Cajun cooking — crawfish beignets and shrimp grits.', cuisine_tags: ['american', 'creole', 'cajun'], dietary_tags: ['vegetarian'], price_avg: 25, address: '652 Polk St, San Francisco, CA 94102', lat: 37.7836, long: -122.4189, hours: 'Mon-Sun 07:00-19:00', avg_rating: 4.4 },
  { name: 'Swan Oyster Depot', description: 'Century-old marble seafood counter with 18 stools — go for the crab, oysters, and chowder.', cuisine_tags: ['american', 'seafood'], dietary_tags: ['gluten-free', 'nut-free'], price_avg: 45, address: '1517 Polk St, San Francisco, CA 94109', lat: 37.7906, long: -122.4204, hours: 'Mon-Sat 10:30-17:30', avg_rating: 4.6 },
  { name: 'Old Jerusalem', description: 'Family-run Palestinian kitchen for hummus, maqluba, and charcoal-grilled kebabs.', cuisine_tags: ['middle-eastern', 'palestinian'], dietary_tags: ['vegetarian', 'vegan', 'halal'], price_avg: 22, address: '2966 Mission St, San Francisco, CA 94110', lat: 37.7503, long: -122.4184, hours: 'Mon-Sun 11:00-22:00', avg_rating: 4.4 },
  { name: 'Beit Rima', description: 'Sunny Castro spot for Levantine comfort food — mujadara, msakhan, and crispy chicken.', cuisine_tags: ['middle-eastern', 'levantine'], dietary_tags: ['vegetarian', 'vegan', 'halal', 'gluten-free'], price_avg: 28, address: '138 Church St, San Francisco, CA 94114', lat: 37.7679, long: -122.4288, hours: 'Mon-Sun 11:00-22:00', avg_rating: 4.4 },
  { name: 'Aslam\'s Rasoi', description: 'Bustling Valencia St spot for Pakistani karahi, seekh kebabs, and buttery garlic naan.', cuisine_tags: ['pakistani'], dietary_tags: ['halal', 'vegetarian', 'gluten-free'], price_avg: 25, address: '1037 Valencia St, San Francisco, CA 94110', lat: 37.7562, long: -122.4210, hours: 'Mon-Sun 11:00-22:00', avg_rating: 4.3 },
  { name: 'Zamzam Kabab House', description: 'Cozy Afghan kitchen for kabuli palaw, mantu dumplings, and charcoal lamb kebabs.', cuisine_tags: ['afghan'], dietary_tags: ['halal', 'vegetarian', 'gluten-free'], price_avg: 24, address: '4113 Geary Blvd, San Francisco, CA 94118', lat: 37.7810, long: -122.4640, hours: 'Mon-Sun 11:00-22:00', avg_rating: 4.4 },
  { name: 'Cafe Ethiopia', description: 'Long-running Mission spot serving spongy injera with spicy doro wat and veggie combos.', cuisine_tags: ['ethiopian'], dietary_tags: ['vegetarian', 'vegan', 'gluten-free', 'dairy-free'], price_avg: 22, address: '878 Valencia St, San Francisco, CA 94110', lat: 37.7592, long: -122.4213, hours: 'Mon-Sun 11:00-22:00', avg_rating: 4.3 },
  { name: 'Bissap Baobab', description: 'Colorful Senegalese kitchen and bar for thieboudienne and hibiscus juice.', cuisine_tags: ['west-african', 'senegalese'], dietary_tags: ['vegetarian', 'vegan', 'gluten-free', 'dairy-free'], price_avg: 28, address: '3372 19th St, San Francisco, CA 94110', lat: 37.7602, long: -122.4210, hours: 'Tue-Sun 17:00-22:00', avg_rating: 4.2 },
  { name: 'Kaiyō', description: 'Nikkei (Japanese-Peruvian) dining room with lush decor, tiradito, and pisco cocktails.', cuisine_tags: ['japanese', 'nikkei'], dietary_tags: ['gluten-free', 'dairy-free'], price_avg: 60, address: '1838 Union St, San Francisco, CA 94123', lat: 37.7975, long: -122.4310, hours: 'Tue-Sun 17:00-22:00', avg_rating: 4.5 },
  { name: 'Limón', description: 'Vibrant dining room for Peruvian lomo saltado, ceviche, and pisco sours.', cuisine_tags: ['latin-american', 'peruvian'], dietary_tags: ['gluten-free', 'dairy-free'], price_avg: 35, address: '1001 S Van Ness Ave, San Francisco, CA 94110', lat: 37.7556, long: -122.4166, hours: 'Tue-Sun 17:00-22:00', avg_rating: 4.3 },
  { name: 'Pica Pica', description: 'Venezuelan arepa and cachapa spot with gluten-free corn pockets and plantains.', cuisine_tags: ['latin-american', 'venezuelan'], dietary_tags: ['gluten-free', 'vegetarian', 'vegan', 'dairy-free'], price_avg: 18, address: '401 Valencia St, San Francisco, CA 94103', lat: 37.7670, long: -122.4220, hours: 'Mon-Sun 11:00-22:00', avg_rating: 4.3 },
  { name: 'El Sur', description: 'Empanada shop selling flaky Argentine empanadas with chimichurri.', cuisine_tags: ['latin-american', 'argentine'], dietary_tags: ['nut-free'], price_avg: 15, address: '699 Valencia St, San Francisco, CA 94110', lat: 37.7615, long: -122.4216, hours: 'Mon-Sun 11:00-22:00', avg_rating: 4.5 },
  { name: 'Aziza', description: 'Refined Moroccan destination in the Outer Richmond for basteeya, tagines, and saffron cocktails.', cuisine_tags: ['north-african', 'moroccan'], dietary_tags: ['vegetarian', 'vegan', 'gluten-free', 'halal'], price_avg: 60, address: '5800 Geary Blvd, San Francisco, CA 94121', lat: 37.7802, long: -122.4788, hours: 'Tue-Sun 17:00-22:00', avg_rating: 4.4 },
  { name: 'Troya', description: 'Inner Richmond Turkish spot for lamb adana, mezze, and manti dumplings.', cuisine_tags: ['mediterranean', 'turkish'], dietary_tags: ['vegetarian', 'halal', 'gluten-free'], price_avg: 30, address: '349 Clement St, San Francisco, CA 94118', lat: 37.7828, long: -122.4640, hours: 'Mon-Sun 11:00-22:00', avg_rating: 4.3 },
  { name: 'La Santaneca', description: 'Excelsior pupuseria griddling cheese-and-loroco pupusas with curtido.', cuisine_tags: ['latin-american', 'salvadoran'], dietary_tags: ['vegetarian', 'gluten-free'], price_avg: 15, address: '3781 Mission St, San Francisco, CA 94110', lat: 37.7360, long: -122.4230, hours: 'Mon-Sun 11:00-22:00', avg_rating: 4.4 },
  { name: 'Rijltje', description: 'Snug spot for an Indonesian rijsttafel spread — rendang, satay, and sambal sides.', cuisine_tags: ['indonesian'], dietary_tags: ['gluten-free', 'dairy-free'], price_avg: 32, address: '2214 Polk St, San Francisco, CA 94109', lat: 37.7960, long: -122.4220, hours: 'Tue-Sun 17:00-22:00', avg_rating: 4.3 },
  { name: 'Barcha', description: 'Downtown Basque-Spanish tapas bar for paella, jamón, and gilda pintxos.', cuisine_tags: ['spanish', 'basque'], dietary_tags: ['vegetarian', 'gluten-free'], price_avg: 45, address: '28 Fremont St, San Francisco, CA 94105', lat: 37.7910, long: -122.3970, hours: 'Tue-Sun 17:00-22:00', avg_rating: 4.2 },
  { name: 'Espetus Churrascaria', description: 'All-you-can-eat Brazilian rodizio near the Symphony, with skewers of picanha.', cuisine_tags: ['latin-american', 'brazilian'], dietary_tags: ['gluten-free'], price_avg: 65, address: '1686 Market St, San Francisco, CA 94102', lat: 37.7726, long: -122.4218, hours: 'Tue-Sun 17:00-22:00', avg_rating: 4.4 },
  { name: 'Helmand Palace', description: 'Elegant Russian Hill Afghan restaurant known for kaddo (pumpkin) and aushak dumplings.', cuisine_tags: ['afghan'], dietary_tags: ['halal', 'vegetarian', 'gluten-free'], price_avg: 35, address: '2424 Van Ness Ave, San Francisco, CA 94109', lat: 37.7975, long: -122.4240, hours: 'Tue-Sun 17:00-22:00', avg_rating: 4.4 },
  { name: 'Rintaro', description: 'Mission izakaya crafting hand-made udon and binchotan-grilled skewers in a cedar-lined room.', cuisine_tags: ['japanese', 'izakaya'], dietary_tags: ['shellfish-free'], price_avg: 55, address: '82 14th St, San Francisco, CA 94103', lat: 37.7686, long: -122.4155, hours: 'Tue-Sun 17:00-22:00', avg_rating: 4.5 },
  { name: 'El Techo', description: 'Rooftop Latin-American cantina with skyline views, ceviche, and frozen palomas.', cuisine_tags: ['latin-american'], dietary_tags: ['gluten-free', 'vegetarian'], price_avg: 40, address: '2516 Mission St, San Francisco, CA 94110', lat: 37.7562, long: -122.4188, hours: 'Wed-Sun 16:00-23:00', avg_rating: 4.2 },
  { name: 'Zuni Bakery Corner', description: 'Cozy Hayes Valley café for sourdough toasts, seasonal galettes, and pour-over coffee.', cuisine_tags: ['american', 'cafe'], dietary_tags: ['vegetarian', 'nut-free'], price_avg: 18, address: '598 Hayes St, San Francisco, CA 94102', lat: 37.7764, long: -122.4260, hours: 'Mon-Sun 07:00-16:00', avg_rating: 4.3 },
  { name: 'Bini\'s Kitchen', description: 'SoMa Nepali spot beloved for momos and chicken curry bowls.', cuisine_tags: ['nepali'], dietary_tags: ['gluten-free', 'vegetarian', 'halal'], price_avg: 20, address: '1001 Howard St, San Francisco, CA 94103', lat: 37.7787, long: -122.4090, hours: 'Mon-Fri 11:00-15:00', avg_rating: 4.5 },
  { name: 'Reem\'s California', description: 'Arab street-food bakery in the Mission famous for man\'oushe flatbreads and knafeh.', cuisine_tags: ['middle-eastern', 'levantine'], dietary_tags: ['vegetarian', 'vegan', 'halal'], price_avg: 22, address: '2901 Mission St, San Francisco, CA 94110', lat: 37.7503, long: -122.4184, hours: 'Wed-Sun 09:00-20:00', avg_rating: 4.4 },
  { name: 'The Bird', description: 'Downtown counter slinging crispy fried-chicken sandwiches and shoestring fries.', cuisine_tags: ['american', 'southern'], dietary_tags: ['nut-free'], price_avg: 16, address: '115 New Montgomery St, San Francisco, CA 94105', lat: 37.7873, long: -122.4008, hours: 'Mon-Sat 11:00-20:00', avg_rating: 4.3 },
  { name: 'Nari', description: 'Ambitious Thai in Japantown from the Kin Khao team, plating regional curries and crudo.', cuisine_tags: ['thai'], dietary_tags: ['gluten-free', 'vegetarian'], price_avg: 65, address: '1625 Post St, San Francisco, CA 94115', lat: 37.7855, long: -122.4310, hours: 'Wed-Sun 17:00-22:00', avg_rating: 4.5 },
  { name: 'Media Noche', description: 'Bright Mission ventanita for Cuban sandwiches, plantain chips, and guava pastries.', cuisine_tags: ['caribbean', 'cuban'], dietary_tags: ['vegetarian'], price_avg: 18, address: '3465 19th St, San Francisco, CA 94110', lat: 37.7601, long: -122.4210, hours: 'Mon-Sun 11:00-21:00', avg_rating: 4.2 },
  { name: 'Palm City', description: 'Outer Sunset wine bar and hoagie shop with West Coast Italian subs and natural wine.', cuisine_tags: ['italian', 'american'], dietary_tags: ['vegetarian'], price_avg: 25, address: '4002 Judah St, San Francisco, CA 94122', lat: 37.7602, long: -122.5045, hours: 'Wed-Sun 12:00-21:00', avg_rating: 4.4 },
  { name: 'San Tung', description: 'Inner Sunset institution mobbed for dry-fried chicken wings and hand-pulled noodles.', cuisine_tags: ['chinese', 'northern-chinese'], dietary_tags: ['vegetarian'], price_avg: 24, address: '1031 Irving St, San Francisco, CA 94122', lat: 37.7639, long: -122.4668, hours: 'Thu-Tue 11:00-21:00', avg_rating: 4.3 },
  { name: 'Turtle Tower', description: 'Tenderloin northern-Vietnamese pho house prized for its clear chicken pho ga.', cuisine_tags: ['vietnamese'], dietary_tags: ['gluten-free', 'dairy-free'], price_avg: 16, address: '645 Larkin St, San Francisco, CA 94109', lat: 37.7842, long: -122.4171, hours: 'Mon-Sun 09:00-19:00', avg_rating: 4.3 },
  { name: 'Frjtz', description: 'Belgian frites-and-crêpes café with a big list of dipping sauces near Hayes Valley.', cuisine_tags: ['belgian', 'european'], dietary_tags: ['vegetarian', 'vegan'], price_avg: 20, address: '579 Hayes St, San Francisco, CA 94102', lat: 37.7765, long: -122.4258, hours: 'Mon-Sun 11:00-21:00', avg_rating: 4.0 },
  { name: 'Un Poste', description: 'Neighborhood Cal-Italian trattoria with wood-fired vegetables and fresh pasta in the Mission.', cuisine_tags: ['italian', 'californian'], dietary_tags: ['vegetarian', 'gluten-free'], price_avg: 48, address: '3138 Mission St, San Francisco, CA 94110', lat: 37.7476, long: -122.4187, hours: 'Tue-Sun 17:00-22:00', avg_rating: 4.4 },
  { name: 'Hilda and Jesse', description: 'North Beach all-day brunch spot for creative eggs Benedict and matcha lattes.', cuisine_tags: ['american', 'brunch'], dietary_tags: ['vegetarian', 'nut-free'], price_avg: 30, address: '701 Union St, San Francisco, CA 94133', lat: 37.8006, long: -122.4093, hours: 'Thu-Mon 09:00-14:00', avg_rating: 4.5 },

  // --- Oakland / East Bay ---
  { name: 'Commis', description: 'Serene Piedmont Ave tasting-menu room, the East Bay\'s Michelin flagship for seasonal Californian cuisine.', cuisine_tags: ['american'], dietary_tags: ['vegetarian', 'gluten-free'], price_avg: 150, address: '3859 Piedmont Ave, Oakland, CA 94611', lat: 37.8266, long: -122.2500, hours: 'Tue-Sun 17:00-22:00', avg_rating: 4.7 },
  { name: 'Comal', description: 'Lively downtown Berkeley Oaxacan spot with a mezcal bar and wood-grilled meats.', cuisine_tags: ['mexican', 'oaxacan'], dietary_tags: ['vegetarian', 'gluten-free'], price_avg: 40, address: '2020 Shattuck Ave, Berkeley, CA 94704', lat: 37.8716, long: -122.2680, hours: 'Tue-Sun 17:00-22:00', avg_rating: 4.4 },
  { name: 'Chez Panisse', description: 'The birthplace of California cuisine — Alice Waters\'s Berkeley landmark with a daily produce-driven menu.', cuisine_tags: ['american'], dietary_tags: ['vegetarian', 'gluten-free'], price_avg: 125, address: '1517 Shattuck Ave, Berkeley, CA 94709', lat: 37.8794, long: -122.2691, hours: 'Tue-Sun 17:00-22:00', avg_rating: 4.6 },
  { name: 'Vik\'s Chaat', description: 'Warehouse-sized Berkeley chaat house packed at lunch for chole bhature and dahi puri.', cuisine_tags: ['indian', 'north-indian'], dietary_tags: ['vegetarian', 'vegan'], price_avg: 18, address: '2390 4th St, Berkeley, CA 94710', lat: 37.8666, long: -122.2996, hours: 'Mon-Sun 07:00-19:00', avg_rating: 4.4 },
  { name: 'FuseBOX', description: 'Tiny, chef-driven West Oakland Korean spot with soulful banchan and house makgeolli.', cuisine_tags: ['korean'], dietary_tags: ['vegetarian', 'vegan'], price_avg: 30, address: '2311A Magnolia St, Oakland, CA 94607', lat: 37.8130, long: -122.2870, hours: 'Tue-Sun 17:00-22:00', avg_rating: 4.5 },
  { name: 'Kholee BBQ', description: 'Korean barbecue in Oakland where you grill marinated galbi and pork belly at the table.', cuisine_tags: ['korean'], dietary_tags: ['gluten-free'], price_avg: 40, address: '372 8th St, Oakland, CA 94607', lat: 37.7995, long: -122.2720, hours: 'Tue-Sun 17:00-22:00', avg_rating: 4.3 },
  { name: 'Millennium', description: 'Elegant, fully vegan fine-dining room in Rockridge with a globally inspired tasting menu.', cuisine_tags: ['american'], dietary_tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free'], price_avg: 70, address: '5912 College Ave, Oakland, CA 94618', lat: 37.8459, long: -122.2519, hours: 'Tue-Sun 17:00-22:00', avg_rating: 4.5 },
  { name: 'Zachary\'s Chicago Pizza', description: 'East Bay institution famous for its baked-to-order stuffed deep-dish Chicago-style pizza.', cuisine_tags: ['american', 'chicago-style'], dietary_tags: ['vegetarian'], price_avg: 25, address: '5801 College Ave, Oakland, CA 94618', lat: 37.8452, long: -122.2523, hours: 'Mon-Sun 11:00-22:00', avg_rating: 4.5 },
  { name: 'Tanglad', description: 'Modern Filipino kitchen in Berkeley plating adobo, kare-kare, and ube desserts.', cuisine_tags: ['filipino'], dietary_tags: ['gluten-free', 'dairy-free'], price_avg: 30, address: '1799 University Ave, Berkeley, CA 94703', lat: 37.8720, long: -122.2740, hours: 'Tue-Sun 17:00-22:00', avg_rating: 4.4 },
  { name: 'Teni East Kitchen', description: 'Modern Burmese-Shan cooking in Oakland with tea-leaf salad and pork-belly curry.', cuisine_tags: ['burmese', 'shan'], dietary_tags: ['vegetarian', 'vegan', 'gluten-free'], price_avg: 30, address: '4015 Broadway, Oakland, CA 94611', lat: 37.8286, long: -122.2637, hours: 'Tue-Sun 17:00-22:00', avg_rating: 4.4 },
  { name: 'Miss Ollie\'s', description: 'Old Oakland Caribbean kitchen famous for skillet-fried chicken and callaloo.', cuisine_tags: ['caribbean'], dietary_tags: ['gluten-free', 'dairy-free'], price_avg: 28, address: '901 Washington St, Oakland, CA 94607', lat: 37.8010, long: -122.2735, hours: 'Tue-Sat 11:00-21:00', avg_rating: 4.5 },
  { name: 'Burma Superstar Oakland', description: 'Temescal outpost of the tea-leaf-salad favorite with coconut chicken noodles.', cuisine_tags: ['burmese'], dietary_tags: ['vegetarian', 'vegan'], price_avg: 30, address: '4721 Telegraph Ave, Oakland, CA 94609', lat: 37.8352, long: -122.2630, hours: 'Mon-Sun 11:00-21:30', avg_rating: 4.4 },
  { name: 'Homeroom', description: 'Rockridge mac-and-cheese specialist with a dozen riffs and a cozy college vibe.', cuisine_tags: ['american', 'comfort'], dietary_tags: ['vegetarian', 'gluten-free'], price_avg: 22, address: '400 40th St, Oakland, CA 94609', lat: 37.8288, long: -122.2620, hours: 'Mon-Sun 11:00-21:00', avg_rating: 4.3 },
  { name: 'Cholita Linda', description: 'Temescal taqueria whose Baja fish tacos and carnitas draw daily lines.', cuisine_tags: ['mexican', 'baja'], dietary_tags: ['gluten-free', 'dairy-free'], price_avg: 18, address: '4923 Telegraph Ave, Oakland, CA 94609', lat: 37.8366, long: -122.2628, hours: 'Tue-Sun 11:00-20:00', avg_rating: 4.5 },
  { name: 'Great China', description: 'Berkeley Chinese landmark celebrated for double-skin salad and Peking duck.', cuisine_tags: ['chinese'], dietary_tags: ['vegetarian'], price_avg: 35, address: '2190 Bancroft Way, Berkeley, CA 94704', lat: 37.8686, long: -122.2680, hours: 'Wed-Mon 11:00-21:00', avg_rating: 4.3 },
  { name: 'Ippuku', description: 'Berkeley izakaya for yakitori, shochu, and binchotan-grilled skewers.', cuisine_tags: ['japanese', 'izakaya'], dietary_tags: ['shellfish-free'], price_avg: 40, address: '2130 Center St, Berkeley, CA 94704', lat: 37.8695, long: -122.2685, hours: 'Tue-Sun 17:00-22:00', avg_rating: 4.4 },
  { name: 'Juanita & Maude', description: 'Albany bistro with a seasonal Cal-Mediterranean menu and a lively bar.', cuisine_tags: ['mediterranean', 'californian'], dietary_tags: ['vegetarian', 'gluten-free'], price_avg: 55, address: '825 San Pablo Ave, Albany, CA 94706', lat: 37.8880, long: -122.2977, hours: 'Wed-Sun 17:00-21:00', avg_rating: 4.5 },

  // --- Peninsula / South Bay ---
  { name: 'Oren\'s Hummus', description: 'Downtown Palo Alto favorite for silky, house-ground Israeli hummus and charred shawarma.', cuisine_tags: ['middle-eastern', 'israeli'], dietary_tags: ['vegetarian', 'vegan', 'gluten-free', 'halal', 'kosher'], price_avg: 25, address: '261 University Ave, Palo Alto, CA 94301', lat: 37.4459, long: -122.1607, hours: 'Mon-Sun 11:00-22:00', avg_rating: 4.3 },
  { name: 'Falafel Stop', description: 'Cult Sunnyvale counter frying crisp Levantine falafel and stuffing generous shawarma pitas.', cuisine_tags: ['middle-eastern', 'levantine'], dietary_tags: ['vegetarian', 'vegan', 'halal'], price_avg: 15, address: '1325 Sunnyvale Saratoga Rd, Sunnyvale, CA 94087', lat: 37.3610, long: -122.0323, hours: 'Mon-Sun 11:00-22:00', avg_rating: 4.5 },
  { name: 'Zola', description: 'Warm Palo Alto bistro serving seasonal Provençal-French plates and craft cocktails.', cuisine_tags: ['french', 'provencal'], dietary_tags: ['vegetarian'], price_avg: 60, address: '565 Bryant St, Palo Alto, CA 94301', lat: 37.4447, long: -122.1618, hours: 'Tue-Sun 17:00-22:00', avg_rating: 4.4 },
  { name: 'Back A Yard', description: 'Downtown San Jose grill fragrant with Jamaican jerk chicken, oxtail, and plantains.', cuisine_tags: ['caribbean', 'jamaican'], dietary_tags: ['gluten-free', 'dairy-free'], price_avg: 25, address: '80 N Market St, San Jose, CA 95113', lat: 37.3369, long: -121.8934, hours: 'Mon-Sun 11:00-22:00', avg_rating: 4.4 },
  { name: 'Din Tai Fung', description: 'The famed chain where chefs pleat delicate Taiwanese xiao long bao behind glass.', cuisine_tags: ['taiwanese'], dietary_tags: ['vegetarian'], price_avg: 35, address: '2855 Stevens Creek Blvd, Santa Clara, CA 95050', lat: 37.3230, long: -121.9490, hours: 'Mon-Sun 11:00-22:00', avg_rating: 4.5 },
  { name: 'Pho Kim Long', description: 'Cavernous, always-open San Jose pho house ladling aromatic beef broth over rice noodles.', cuisine_tags: ['vietnamese'], dietary_tags: ['gluten-free', 'dairy-free'], price_avg: 18, address: '1215 Lick Ave, San Jose, CA 95110', lat: 37.3130, long: -121.8790, hours: 'Mon-Sun 11:00-00:00', avg_rating: 4.2 },
  { name: 'Sushi Sam\'s Edomata', description: 'Traditional San Mateo sushi bar prized for pristine Edomae-style nigiri and omakase.', cuisine_tags: ['japanese', 'edomae-sushi'], dietary_tags: ['gluten-free', 'dairy-free'], price_avg: 55, address: '218 E 3rd Ave, San Mateo, CA 94401', lat: 37.5652, long: -122.3235, hours: 'Tue-Sun 17:00-22:00', avg_rating: 4.6 },
  { name: 'Bevri', description: 'Bright Palo Alto kitchen for Georgian khachapuri cheese boats and khinkali dumplings.', cuisine_tags: ['georgian'], dietary_tags: ['vegetarian'], price_avg: 35, address: '162 University Ave, Palo Alto, CA 94301', lat: 37.4460, long: -122.1620, hours: 'Tue-Sun 17:00-22:00', avg_rating: 4.4 },
  { name: 'Zareen\'s', description: 'Mountain View Pakistani-Indian favorite for chicken tikka, nihari, and mango lassi.', cuisine_tags: ['pakistani', 'indian'], dietary_tags: ['halal', 'vegetarian', 'gluten-free'], price_avg: 20, address: '1477 Plymouth St, Mountain View, CA 94043', lat: 37.4139, long: -122.0770, hours: 'Mon-Sun 11:00-21:00', avg_rating: 4.5 },
  { name: 'Tel Aviv Fusion', description: 'Sunnyvale Israeli grill for shawarma plates, sabich, and fresh hummus.', cuisine_tags: ['middle-eastern', 'israeli'], dietary_tags: ['halal', 'vegetarian', 'vegan', 'gluten-free'], price_avg: 22, address: '134 S Murphy Ave, Sunnyvale, CA 94086', lat: 37.3766, long: -122.0300, hours: 'Mon-Sat 11:00-21:00', avg_rating: 4.4 },
  { name: 'Sumika', description: 'Los Altos robatayaki grill specializing in charcoal chicken and Japanese comfort dishes.', cuisine_tags: ['japanese', 'robata'], dietary_tags: ['shellfish-free'], price_avg: 35, address: '236 Central Plaza, Los Altos, CA 94022', lat: 37.3772, long: -122.1140, hours: 'Tue-Sun 17:00-21:30', avg_rating: 4.5 },
  { name: 'La Viga Seafood', description: 'Redwood City marisquería for aguachile, ceviche tostadas, and whole fried fish.', cuisine_tags: ['mexican', 'seafood'], dietary_tags: ['gluten-free', 'dairy-free'], price_avg: 28, address: '1772 Broadway, Redwood City, CA 94063', lat: 37.4855, long: -122.2280, hours: 'Mon-Sun 11:00-21:00', avg_rating: 4.4 },
  { name: 'Rangoon Ruby', description: 'Palo Alto Burmese dining room known for tea-leaf salad and coconut noodle curry.', cuisine_tags: ['burmese'], dietary_tags: ['vegetarian', 'vegan', 'gluten-free'], price_avg: 30, address: '445 Emerson St, Palo Alto, CA 94301', lat: 37.4450, long: -122.1630, hours: 'Mon-Sun 11:00-21:30', avg_rating: 4.2 },
  { name: 'Smoking Pig BBQ', description: 'San Jose barbecue joint piling brisket, tri-tip, and pulled pork over Texas toast.', cuisine_tags: ['american', 'barbecue'], dietary_tags: ['gluten-free'], price_avg: 25, address: '1144 N 4th St, San Jose, CA 95112', lat: 37.3620, long: -121.9010, hours: 'Tue-Sun 11:00-20:00', avg_rating: 4.4 },
  { name: 'Falafel\'s Drive-In', description: 'Beloved San Jose drive-in for stuffed falafel pitas and banana shakes.', cuisine_tags: ['middle-eastern'], dietary_tags: ['vegetarian', 'vegan', 'halal'], price_avg: 14, address: '2301 Stevens Creek Blvd, San Jose, CA 95128', lat: 37.3220, long: -121.9350, hours: 'Mon-Sat 10:00-20:00', avg_rating: 4.5 },

  // --- Marin / North Bay ---
  { name: 'Sol Food', description: 'Sunny San Rafael Puerto Rican kitchen famous for its garlicky pollo al ajillo and plantains.', cuisine_tags: ['caribbean', 'puerto-rican'], dietary_tags: ['gluten-free', 'vegetarian', 'dairy-free'], price_avg: 25, address: '901 Lincoln Ave, San Rafael, CA 94901', lat: 37.9762, long: -122.5222, hours: 'Mon-Sun 11:00-22:00', avg_rating: 4.5 },
  { name: 'Sushi Ran', description: 'Sausalito\'s destination sushi bar blending Edomae technique with a curated sake list.', cuisine_tags: ['japanese', 'edomae-sushi'], dietary_tags: ['gluten-free', 'dairy-free'], price_avg: 80, address: '107 Caledonia St, Sausalito, CA 94965', lat: 37.8570, long: -122.4850, hours: 'Tue-Sun 17:00-22:00', avg_rating: 4.6 },
  { name: 'Fish.', description: 'Waterfront Sausalito seafood shack serving sustainable catch and a killer crab roll.', cuisine_tags: ['american', 'seafood'], dietary_tags: ['gluten-free'], price_avg: 45, address: '350 Harbor Dr, Sausalito, CA 94965', lat: 37.8637, long: -122.4820, hours: 'Mon-Sun 11:00-22:00', avg_rating: 4.4 },
  { name: 'Bar Bocce', description: 'Casual bayside spot with wood-fired Neapolitan pizzas and a sandy bocce court.', cuisine_tags: ['italian', 'neapolitan'], dietary_tags: ['vegetarian'], price_avg: 35, address: '1250 Bridgeway, Sausalito, CA 94965', lat: 37.8620, long: -122.4835, hours: 'Mon-Sun 11:00-22:00', avg_rating: 4.3 },
  { name: 'Poggio Trattoria', description: 'Sausalito northern-Italian trattoria with house-made pasta and a wood-fired grill.', cuisine_tags: ['italian', 'northern-italian'], dietary_tags: ['vegetarian', 'gluten-free'], price_avg: 55, address: '777 Bridgeway, Sausalito, CA 94965', lat: 37.8570, long: -122.4790, hours: 'Mon-Sun 11:30-21:30', avg_rating: 4.4 },
  { name: 'Sushi to Dai For', description: 'Corte Madera neighborhood sushi bar with generous nigiri and creative rolls.', cuisine_tags: ['japanese', 'sushi'], dietary_tags: ['gluten-free', 'dairy-free'], price_avg: 45, address: '38 Miller Ave, Mill Valley, CA 94941', lat: 37.9060, long: -122.5450, hours: 'Tue-Sun 17:00-21:00', avg_rating: 4.4 },
  { name: 'Arti Cafe', description: 'Lagunitas Indian kitchen for creamy kormas, dosas, and garlic naan in West Marin.', cuisine_tags: ['indian'], dietary_tags: ['vegetarian', 'vegan', 'gluten-free'], price_avg: 28, address: '60 Sir Francis Drake Blvd, Lagunitas, CA 94938', lat: 38.0110, long: -122.6890, hours: 'Wed-Mon 12:00-21:00', avg_rating: 4.3 },
  { name: 'Fred\'s Coffee Shop', description: 'Sausalito greasy-spoon diner famous for deep-fried french toast and big breakfasts.', cuisine_tags: ['american', 'diner'], dietary_tags: ['vegetarian', 'nut-free'], price_avg: 18, address: '1917 Bridgeway, Sausalito, CA 94965', lat: 37.8680, long: -122.4900, hours: 'Mon-Sun 06:30-14:00', avg_rating: 4.3 },
  { name: 'Playa', description: 'Mill Valley coastal-Mexican spot for wood-grilled fish tacos and mezcal cocktails.', cuisine_tags: ['mexican'], dietary_tags: ['gluten-free', 'vegetarian'], price_avg: 35, address: '41 Throckmorton Ave, Mill Valley, CA 94941', lat: 37.9060, long: -122.5460, hours: 'Mon-Sun 11:30-21:00', avg_rating: 4.2 },

]

async function main() {
  console.log(`Seeding ${restaurants.length} restaurants...`)
  await prisma.$executeRawUnsafe(
    'TRUNCATE TABLE "Restaurant" RESTART IDENTITY CASCADE'
  )
  const result = await prisma.restaurant.createMany({ data: restaurants })
  console.log(`Inserted ${result.count} restaurants.`)
  console.log(`Total restaurants in DB: ${await prisma.restaurant.count()}`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exitCode = 1
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
